services:
  blaze-frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        PORT: ${PORT}
        NEXT_PUBLIC_CONTRACT_ADDRESS: ${NEXT_PUBLIC_CONTRACT_ADDRESS}
        NEXT_PUBLIC_APTOS_NETWORK: ${NEXT_PUBLIC_APTOS_NETWORK}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET: ${NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET}
        NEXT_PUBLIC_CONTRACT_ADDRESS: ${NEXT_PUBLIC_CONTRACT_ADDRESS}
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      NEXT_PUBLIC_CONTRACT_ADDRESS: ${NEXT_PUBLIC_CONTRACT_ADDRESS}
      NEXT_PUBLIC_APTOS_NETWORK: ${NEXT_PUBLIC_APTOS_NETWORK}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET: ${NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET}
      NEXT_PUBLIC_CONTRACT_ADDRESS: ${NEXT_PUBLIC_CONTRACT_ADDRESS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blaze-frontend.rule=Host(`blaze.jovihost.site`)"
      - "traefik.http.routers.blaze-frontend.entrypoints=websecure"
      - "traefik.http.routers.blaze-frontend.tls.certResolver=letsencrypt"
      - "traefik.http.services.blaze-frontend.loadbalancer.server.port=${PORT}"
    networks:
      - dokploy-network


networks:
  dokploy-network:
    external: true
